import React from "react";

const TermsCondition = () => {
  return (
    <>
      <div className="container mt-5 ">
        <div className="row justify-content-center">
          <div className="col-md-12">
            <div className="card bg-light">
              <div className="card-body">
                <h1 className="card-title text-center text-primary mb-4">
                  Terms of Use
                </h1>
                <p className="card-text">
                  This document is an electronic record in terms of Information
                  Technology Act, 2000 (“IT ACT”), as applicable and the
                  provisions pertaining to electronic records in various
                  statutes as amended by the IT Act and is published in
                  accordance with the Applicable Laws, including the Consumer
                  Protection (E-Commerce) Rules, 2020, that require publishing
                  the rules and regulations, Privacy Policy and terms and
                  conditions for access or usage of the website. This electronic
                  record is generated by a computer system and does not require
                  any physical or digital signatures.
                </p>
                <p className="card-text">
                  Welcome to Healthify hosted on{" "}
                  <a href="https://www.healthify.com">www.healthify.com</a>{" "}
                  (hereinafter referred to as the “Website”) and/or on a mobile
                  application platform or any other digital platform developed
                  or sourced by Expedient Healthcare Marketing Private Limited
                  (hereinafter collectively referred to as the “Platform”).
                </p>
                <p className="card-text">
                  The content of this Platform pertains to Healthify and is the
                  property of Expedient Healthcare Marketing Private Limited
                  having its registered office at Plot No. 518, Udyog Vihar,
                  Phase III, Gurugram, Haryana, India – 122016 operating under
                  the brand name Healthify (hereinafter referred to as
                  “Healthify/the Company”, which expression shall, unless it be
                  repugnant to the context or meaning thereof, be deemed to mean
                  and include its wholly owned subsidiaries, successors and
                  permitted assigns). Healthify is India’s largest test @home
                  service and assures quality collection and testing across its
                  network of labs and hundreds of full-time phlebotomists.
                </p>
                <p className="card-text">
                  By using the Platform, You represent that you have read and
                  agree to be bound by the terms of this Agreement, as well as
                  any other guidelines, privacy policy, rules and additional
                  terms referenced herein. The Terms of Use (defined
                  hereinafter) sets out the legally binding terms with respect
                  to your access and use of the Platform and our provision of
                  the Services (as defined below).
                </p>
                <p className="card-text">
                  Please read these Terms of Use carefully. Your access to
                  Platform and/or use of the Service (defined hereinafter)
                  constitutes your acceptance of all the provisions of these
                  Terms of Use and Privacy Policy. Healthify reserves the right
                  to modify these Terms of Use without any prior notice. You are
                  advised to regularly review and access these Terms of Use. If
                  you do not agree with any of the Terms of Use and any
                  amendments thereto, you must not access the Platform and/or
                  use the Services offered by Healthify.
                </p>
                <div className="mt-4">
                  <h5 className="mb-3">Key Points:</h5>
                  <ul className="list-group list-group-flush">
                    <li className="list-group-item">
                      This is an electronic record under the IT Act, 2000.
                    </li>
                    <li className="list-group-item">
                      Healthify is hosted on www.healthify.com and other
                      platforms by Expedient Healthcare Marketing Private
                      Limited.
                    </li>
                    <li className="list-group-item">
                      By using the Platform, you agree to the Terms of Use and
                      Privacy Policy.
                    </li>
                    <li className="list-group-item">
                      Healthify reserves the right to modify the Terms of Use
                      without prior notice.
                    </li>
                  </ul>
                </div>
                <div className="mt-4">
                  <h5 className="mb-3">Eligibility</h5>
                  <ul className="list-group list-group-flush">
                    <li className="list-group-item">
                      By using the Platform and/or availing the Services, You
                      represent and warrant that You have the right, authority,
                      and capacity to agree with the policies of Healthify, in
                      respect of the Services being offered and to abide by all
                      of the conditions set forth herein.
                    </li>
                    <li className="list-group-item">
                      You are responsible for all the transactions you make
                      under your name or account.
                    </li>
                    <li className="list-group-item">
                      You are 18 years of age or over and have the legal rights
                      to agree with the form of the binding contract in your
                      jurisdiction.
                    </li>
                    <li className="list-group-item">
                      You signify and warrant to the Company that you will use
                      the Services in a manner dependable with all the pertinent
                      rules and regulations.
                    </li>
                  </ul>
                </div>

                <div className="mt-4">
                  <h5 className="mb-3">Services</h5>
                  <ol className="list-group list-group-numbered list-group-flush">
                    <li className="list-group-item">
                      The use of this Platform entitles You, to avail certain
                      services as provided in the following clauses and
                      interpretation of the term 'Services' shall be done
                      accordingly depending upon the context.
                    </li>
                    <li className="list-group-item">
                      The following services are offered by Healthify through
                      its Platform:
                      <ol className="list-group list-group-flush">
                        <li className="list-group-item">
                          Health investigations/test services at home (sample
                          collection from Your doorstep).
                        </li>
                        <li className="list-group-item">
                          Health investigations/diagnosis/scans services from
                          test centres/laboratories.
                        </li>
                        <li className="list-group-item">Doctor consultation</li>
                        <li className="list-group-item">
                          Dietician consultation
                        </li>
                        <li className="list-group-item">Sale of supplements</li>
                        <li className="list-group-item">
                          Any other services/goods that may be offered by the
                          Company through its Platform
                        </li>
                      </ol>
                    </li>
                    <li className="list-group-item">
                      The Company reserves the right to change the nature or
                      price payable in connection with Services at its sole
                      discretion. Such change may be notified by publishing the
                      same on the Platform.
                    </li>
                  </ol>
                </div>

                <div className="mt-4">
                  <h5 className="mb-3">Eligibility</h5>
                  <ul className="list-group list-group-flush">
                    <li className="list-group-item">
                      By using the Platform and/or availing the Services, You
                      represent and warrant that You have the right, authority,
                      and capacity to agree with the policies of Healthify, in
                      respect of the Services being offered and to abide by all
                      of the conditions set forth herein.
                    </li>
                    <li className="list-group-item">
                      You are responsible for all the transactions you make
                      under your name or account.
                    </li>
                    <li className="list-group-item">
                      You are 18 years of age or over and have the legal rights
                      to agree with the form of the binding contract in your
                      jurisdiction.
                    </li>
                    <li className="list-group-item">
                      You signify and warrant to the Company that you will use
                      the Services in a manner dependable with all the pertinent
                      rules and regulations.
                    </li>
                  </ul>
                </div>

                <div className="mt-4">
                  <h5 className="mb-3">Services</h5>
                  <ol className="list-group list-group-numbered list-group-flush">
                    <li className="list-group-item">
                      The use of this Platform entitles You, to avail certain
                      services as provided in the following clauses and
                      interpretation of the term 'Services' shall be done
                      accordingly depending upon the context.
                    </li>
                    <li className="list-group-item">
                      The following services are offered by Healthify through
                      its Platform:
                      <ol className="list-group list-group-flush">
                        <li className="list-group-item">
                          Health investigations/test services at home (sample
                          collection from Your doorstep).
                        </li>
                        <li className="list-group-item">
                          Health investigations/diagnosis/scans services from
                          test centres/laboratories.
                        </li>
                        <li className="list-group-item">Doctor consultation</li>
                        <li className="list-group-item">
                          Dietician consultation
                        </li>
                        <li className="list-group-item">Sale of supplements</li>
                        <li className="list-group-item">
                          Any other services/goods that may be offered by the
                          Company through its Platform
                        </li>
                      </ol>
                    </li>
                    <li className="list-group-item">
                      The Company reserves the right to change the nature or
                      price payable in connection with Services at its sole
                      discretion. Such change may be notified by publishing the
                      same on the Platform.
                    </li>
                  </ol>
                </div>

                <div className="mt-4">
                  <h5 className="mb-3">
                    Sample Collection and Report Generation at Healthify
                  </h5>
                  <p>
                    Sample collection is scheduled on the booking date of tests.
                    You can also reschedule the sample collection as per the
                    available time and slot.
                  </p>
                  <p>
                    You may experience delay in a scheduled sample collection
                    due to factors beyond the reasonable control of Healthify
                    including but not limited to any act of god and any other
                    cause(s) beyond the control of Healthify such as fires,
                    floods, strikes, lockouts, lockdown, curfews, riots or civil
                    commotion, epidemics, pandemics, COVID-restrictions, war,
                    change in the legal/regulatory regime and acts of
                    government, technical failure, political rallies, VIP
                    movements, weather conditions etc. Any delay or cancellation
                    will be timely informed to you by Healthify. Kindly keep a
                    check on messages, WhatsApp and emails regularly for recent
                    updates.
                  </p>
                  <p>
                    Post sample collection, reports are usually generated as per
                    the timeline as communicated to You at the time of booking,
                    however some tests may have longer turnaround time and the
                    same shall be informed to You at the time of sample booking
                    / collection. In exceptional cases due to unforeseen
                    circumstances, there are chances that You may experience
                    delay in release of test results. You hereby agree to bear
                    the delay that You may have to experience. As such, the
                    diagnostic Services should not be availed by You in case of
                    emergency.
                  </p>
                </div>

                <div className="mt-4">
                  <h5 className="mb-3">
                    CONSUMABLES AND TRANSPORTATION CHARGES (C&T Charges)
                  </h5>
                  <p>
                    Here are the terms and conditions regarding Consumables and
                    Transportation Charges:
                  </p>
                  <ol className="list-group list-group-numbered list-group-flush">
                    <li className="list-group-item">
                      Any discount coupons shall not be applied on C&T Charges.
                    </li>
                    <li className="list-group-item">
                      In case of complete booking being rescheduled, C&T Charges
                      shall not be applicable again if already paid by You.
                    </li>
                    {/* Add other C&T Charges here */}
                  </ol>
                </div>

                <div className="mt-4">
                  <h5 className="mb-3">OTHER SERVICES</h5>
                  <p>
                    Here are the terms and conditions for other services
                    offered:
                  </p>
                  <h6 className="mt-3">Radiology</h6>
                  <p>
                    1) You can book the radiology services offered by Healthify
                    through the website or application.
                  </p>
                  {/* Add other terms for Radiology */}
                  <h6 className="mt-3">Dietician Consultation</h6>
                  <p>
                    1) You can avail the dietician consultation offered by
                    Healthify as follows:
                  </p>
                  {/* Add terms for Dietician Consultation */}
                  <h6 className="mt-3">Supplement Sale</h6>
                  <p>
                    1) You can purchase various herbal supplement products
                    offered by Healthify as follows:
                  </p>
                  {/* Add terms for Supplement Sale */}
                </div>

                <div className="mt-4">
                  <h5 className="mb-3">Payment</h5>
                  <p>Here are the payment terms and conditions:</p>
                  <ul className="list-group list-group-flush">
                    <li className="list-group-item">
                      Healthify shall endeavor to provide You with
                      facilities/gateways to pay the fee in consideration of the
                      Services (“Fee”) on the Platform through credit cards
                      (American Express, Visa and Mastercard), debit cards, cash
                      cards, UPI and internet banking.
                    </li>
                    <li className="list-group-item">
                      You shall have to option to pay through the online modes
                      as stated above or through Cash on Delivery “(COD)”.
                    </li>
                    {/* Add other payment terms here */}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="container mt-5">
        <div className="row justify-content-center"></div>
      </div>
    </>
  );
};

export default TermsCondition;
